/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skywds_android_bsdiffpatch_JniApi */

#ifndef _Included_com_skywds_android_bsdiffpatch_JniApi
#define _Included_com_skywds_android_bsdiffpatch_JniApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skywds_android_bsdiffpatch_JniApi
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_skywds_android_bsdiffpatch_JniApi_bspatch
  (JNIEnv *env, jclass jcl, jstring oldPath, jstring newPath, jstring patchPath);

#ifdef __cplusplus
}
#endif
#endif
